### ISSUE TITLE
No errors reported

### ISSUE THREAD

**Issue by samdoran** [Aeron/Mypy.novaextension#2]
### Summary 
I am encountering the same issue as reported in #1. Errors that `mypy` reports when run from the command line are not reported by the extension in Nova.

### Environment
Nova version: 9.3
`mypy` version: 0.950
Python version: 3.10.3
Extension version: 0.1.0
macOS version: 12.3.1 (21E258)

### Additional Information

Example file:

```python
def my_func(arg1: str) -> None:
    print(arg1)

    return 27


my_func(1)
```

Expected results:

```shell
/Users/sdoran/Downloads/test.py:4: error: No return value expected
/Users/sdoran/Downloads/test.py:7: error: Argument 1 to "my_func" has incompatible type "int"; expected "str"
Found 2 errors in 1 file (checked 1 source file)
```

Actual results from Nova extension console:
```
Mypy[13:47:44.101000] Running /Users/sdoran/.pyenv/versions/appomni-dev-3.7.12/bin/mypy --shadow-file .//Users/sdoran/Downloads/test.py /Users/sdoran/Library/Application Support/Nova/Workspaces/951FB00D-2D31-42CF-A475-96B813BBFAF5/cc.aeron.nova-mypy/-837007767.1651600064099.tmp /Users/sdoran/Downloads/test.py
Mypy[13:47:44.175000] Checking /Users/sdoran/Downloads/test.py
Mypy[13:47:44.175000] Found 0 issue(s)
```

**Comment by Aeron** [comment]
Hey, Sam. I’ve checked this case on my system: Nova 9.3, Python 3.10.4, and Mypy 0.950.

The extension version should be 0.1.0, but it’s a typo probably. Everything else is not relevant yet thank you for all the details.

I got the following result:

```log
Mypy[23:15:31.600000] Running /usr/local/asdf/shims/mypy --shadow-file ./playground-2.py /Users/aeron/Library/Application Support/Nova/Workspaces/B3E20458-CF35-4609-A00C-06AD41DB2785/cc.aeron.nova-mypy/2023605783.1651853731596.tmp playground-2.py
Mypy[23:15:32.152000] Checking playground-2.py
Mypy[23:15:32.152000] Found 2 issue(s)
```

So, what could it be? The first things that came to mind:

1. Could you check if `~/.pyenv/versions/appomni-dev-3.7.12/bin/mypy` is 0.950? Just in case there’s another Mypy executable in the PATH.
2. Do you have separate Python in your system? Could you try to specify the exact Python path in extension preferences? Or do you already have one: global or project?
3. Do you have a global Mypy config anywhere? Just as I mentioned in #1.

I don’t think that `pyenv` is directly a reason here. I’m using native `venv`, but this time I used none.

**Comment by samdoran** [comment]
> The extension version should be 0.1.0, but it’s a typo probably.

Yup, sorry about that.

> Could you check if ~/.pyenv/versions/appomni-dev-3.7.12/bin/mypy is 0.950? 

```
> ~/.pyenv/versions/appomni-dev-3.7.12/bin/mypy --version
mypy 0.950 (compiled: no)
```

> Do you have separate Python in your system? Could you try to specify the exact Python path in extension preferences? Or do you already have one: global or project?

I have _many_ Pythons installed.

I only set the executable path in the global extension preference. I haven't set any project specific configs. It looks like the only place to set the Python executable path is in project preferences. I will try that.

My main project does indeed have a `mypy.ini` at the project root. I do not have a global `mypy` config.

For the purpose of this bug report, I used a directory that does not have any configuration files.

```
> ~/.pyenv/versions/appomni-dev-3.7.12/bin/mypy -v ~/Downloads/test.py

LOG:  Mypy Version:           0.950
LOG:  Config File:            Default
...
```

**Comment by samdoran** [comment]
Setting the Python executable path at the project level did not fix the issue.

I also tried using `mypy` with Python 3.10.3.

I set both executable path and Python executable path at the project level:

`/Users/sdoran/.pyenv/versions/mypy-3.10.3/bin/mypy`
`/Users/sdoran/.pyenv/versions/mypy-3.10.3/bin/python`

That still report zero issues:

```
Mypy[15:59:36.512000] Running /Users/sdoran/.pyenv/versions/mypy-3.10.3/bin/mypy --python-executable=/Users/sdoran/.pyenv/versions/mypy-3.10.3/bin/python --shadow-file ./test.py /Users/sdoran/Library/Application Support/Nova/Workspaces/F721BC42-EB6B-4B51-BE11-371EDCEEB52A/cc.aeron.nova-mypy/-1422502683.1651867176506.tmp test.py
Mypy[15:59:36.609000] Checking test.py
Mypy[15:59:36.609000] Found 0 issue(s)
```

I found that running the command from the Nova console manually results in `mypy: can't read file 'test.py': No such file or directory`. Quite curious.

```
> pwd
/Users/sdoran/Downloads

> ls -l test.py
-rw-r--r--@ 1 sdoran  staff  76 May  6 16:10 test.py

> /Users/sdoran/.pyenv/versions/mypy-3.10.3/bin/mypy --python-executable=/Users/sdoran/.pyenv/versions/3.10.3/bin/python3.10 --shadow-file ./test.py "/Users/sdoran/Library/Application Support/Nova/Workspaces/F721BC42-EB6B-4B51-BE11-371EDCEEB52A/cc.aeron.nova-mypy/-1422502683.1651867710272.tmp" test.py
mypy: can't read file 'test.py': No such file or directory
```

**Comment by Aeron** [comment]
Ok, thank you for the details. I’ll try to reproduce it somehow.

**Comment by guillaumealgis** [comment]
4 things I found to be buggy : 

- If using `~` in the path for the mypy executable, this won't be expanded to you home dir, you have to explicitly use an absolute path (e.g. `/Users/guillaume/path/to/bin/mypy`).
- When trying to remove the `tmpPath`, this will crash the extension if the check mode is != of onFileChange (trying to remove a `null` path)
- `mypy` will by default report issues coming from imported modules, and the extension will parse them as coming from the current file. The extension should probably always add [the option `--follow-imports silent`](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-follow-imports) to `mypy` to filter out messages to only the relevant (i.e. current) file.
- The issueMatcher regex is wrong, it doesn't account for error messages without a column number. I had better results with the following config, but be aware that I haven't yet tested it extensively :  



```json
"issueMatchers": {
  "mypy": {
    "pattern": {
      "regexp": "^(.+\\.py):(\\d+):((\\d+):)?\\s(\\w+):\\s(.*)",
      "message": 6,
      "code": 5,
      "line": 2,
      "column": 4,
      "severity": "error"
    }
  }
}
```

A patch is attached, I'd don't have time to provide a proper PR right now but I'll try to get around to it.


[mypy-nova.patch.zip](https://github.com/Aeron/Mypy.novaextension/files/9870062/mypy-nova.patch.zip)

**Comment by samdoran** [comment]
> If using ~ in the path for the mypy executable, this won't be expanded to you home dir

I don't think this is unique to this plugin. I always use absolute paths for executables.

I'll try this out and see if it helps any.

**Comment by guillaumealgis** [comment]
>> If using ~ in the path for the mypy executable, this won't be expanded to you home dir

> I don't think this is unique to this plugin. I always use absolute paths for executables.

Indeed, but expanding such common shorthands would be nice, or at least providing an error message if the binary is not found.

**Comment by samdoran** [comment]
With the above patch, I get results now.

**Comment by samdoran** [comment]
It looks like the error messages I am seeing don't have columns, which is why the regexp change fixes 
```
typing-tests.py:10: error: No return value expected
typing-tests.py:17: error: Argument 1 to "my_other_func" has incompatible type "int"; expected "str"
```

**Comment by samdoran** [comment]
Further scrutiny reveals the fix is indeed making the second group of "digits:" optional. Great work!

**Comment by Aeron** [comment]
Thank you for keep digging, gentlemen. To my shame, I don’t have much attention to doing it at the moment. Yet PRs are always welcome. I’ll do my best to keep the extensions up to date, even if I’m not using Nova.

**Comment by Aeron** [comment]
Also, regarding the `--follow-imports silent` option: if I remember correctly, VS Code extension, for example, does not force this option. That is why each of my project configurations (`pyproject.toml` or `.mypy.ini`) always has it explicitly, despite global settings even.

I’m uncertain if we want to force every extension user to operate it only this way.

**Comment by samdoran** [comment]
I'll work on some PRs. I meant to get to it this week but time got away from me.

**Comment by samdoran** [comment]
I think those PRs cover the items discussed above. I'm open to feedback in the fixes.

**Comment by Aeron** [comment]
Looks good to me. Everything is merged, released, and uploaded to the extension library. Thank you, good sirs 🤜🤛

**Comment by samdoran** [comment]
Thank you so much!
